# Generated by Django 3.1.1 on 2020-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='cover',
            field=models.CharField(default='https://images-na.ssl-images-amazon.com/images/I/61ZNAnIrwwL.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
